language: node.js

sudo: false

cache:
  directories:
    - node_modules

node_js:
    - "5.11"
before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

before_script:
    - npm install --save-dev browser-sync
    - npm install -g gulp
    - npm install --save-dev gulp
    - npm install --save-dev gulp-concat
    - npm install --save-dev gulp-jshint
    - npm install --save-dev gulp-mocha
    - npm install --save-dev gulp-notify
    - npm install --save-dev gulp-plumber
    - npm install --save-dev gulp-uglify
    - npm install --save-dev gulp-watch
    - npm install --save-dev jshint
    - npm install --save-dev jshint-stylish
    - npm install --save-dev nightwatch

    - npm install --save-dev chromedriver
    - npm install --save-dev dotenv
    - npm install --save-dev selenium-server-standalone-jar

script: 
#    - gulp
    - npm run test_single
