language: node.js

sudo: false

cache:
  directories:
    - node_modules

node_js:
    - "5.11.1"

before_script:
    - npm install --save-dev browser-sync
    - npm install -g gulp
    - npm install --save-dev gulp
    - npm install --save-dev gulp-concat
    - npm install --save-dev gulp-jshint
    - npm install --save-dev gulp-mocha
    - npm install --save-dev gulp-notify
    - npm install --save-dev gulp-plumber
    - npm install --save-dev gulp-uglify
    - npm install --save-dev gulp-watch
    - npm install --save-dev jshint
    - npm install --save-dev jshint-stylish
    - npm install --save-dev nightwatch

script: gulp
